import type { Activity } from "@/types/activity"

export const activities: Activity[] = [
  {
    id: 1,
    slug: "atividade-ao-ar-livre",
    likes: 12,
    title: "Atividade ao ar livre",
    content: "Praticar atividades ao ar livre promove saúde física e mental, estimulando o contato com a natureza e fortalecendo vínculos sociais entre os participantes do Centro Dia.",
    media: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=640&h=480&fit=crop",
      alt_text: "Pessoas praticando atividade ao ar livre em um parque",
      caption: null,
    },
    created_at: "2026-04-20T00:00:00+00:00",
  },
  {
    id: 2,
    slug: "oficina-de-pintura",
    likes: 25,
    title: "Oficina de pintura",
    content: "A pintura em telas desenvolve a criatividade, a coordenação motora e a expressão emocional dos assistidos, sendo uma das atividades mais aguardadas da semana no Centro Dia.",
    media: {
      url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=640&h=480&fit=crop",
      alt_text: "Pessoa pintando em tela com tintas coloridas",
      caption: null,
    },
    created_at: "2026-04-15T00:00:00+00:00",
  },
  {
    id: 3,
    slug: "horta-comunitaria",
    likes: 18,
    title: "Horta comunitária",
    content: "A horta comunitária ensina sobre sustentabilidade, alimentação saudável e responsabilidade coletiva, além de proporcionar momentos de relaxamento e conexão com a terra.",
    media: {
      url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=640&h=480&fit=crop",
      alt_text: "Mãos cuidando de plantas em uma horta",
      caption: null,
    },
    created_at: "2026-04-10T00:00:00+00:00",
  },
  {
    id: 4,
    slug: "convivencia-em-grupo",
    likes: 30,
    title: "Convivência em grupo",
    content: "As atividades em grupo fortalecem laços de amizade, desenvolvem habilidades sociais e promovem um ambiente de respeito, inclusão e pertencimento para todos os participantes.",
    media: {
      url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=640&h=480&fit=crop",
      alt_text: "Grupo de pessoas interagindo e sorrindo",
      caption: null,
    },
    created_at: "2026-04-05T00:00:00+00:00",
  },
  {
    id: 5,
    slug: "atividades-fisicas",
    likes: 15,
    title: "Atividades físicas",
    content: "A prática regular de exercícios físicos melhora a qualidade de vida, previne doenças e contribui para o desenvolvimento da autonomia e da autoestima dos assistidos.",
    media: {
      url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=640&h=480&fit=crop",
      alt_text: "Pessoa praticando exercício físico",
      caption: null,
    },
    created_at: "2026-04-01T00:00:00+00:00",
  },
  {
    id: 6,
    slug: "musica-e-expressao",
    likes: 42,
    title: "Música e expressão",
    content: "A música estimula o desenvolvimento cognitivo, emocional e social, permitindo que os assistidos se expressem, criem e se conectem com os outros de forma única e especial.",
    media: {
      url: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=640&h=480&fit=crop",
      alt_text: "Pessoa tocando instrumento musical",
      caption: null,
    },
    created_at: "2026-03-25T00:00:00+00:00",
  },
  {
    id: 7,
    slug: "culinaria-assistida",
    likes: 21,
    title: "Culinária assistida",
    content: "As aulas de culinária desenvolvem autonomia, planejamento e habilidades práticas do dia a dia, além de promover uma alimentação mais saudável e consciente entre os participantes.",
    media: {
      url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=640&h=480&fit=crop",
      alt_text: "Pessoa preparando alimento na cozinha",
      caption: null,
    },
    created_at: "2026-03-20T00:00:00+00:00",
  },
  {
    id: 8,
    slug: "artesanato-manual",
    likes: 19,
    title: "Artesanato",
    content: "O artesanato desenvolve a coordenação motora fina, a paciência e a criatividade, além de gerar produtos únicos que podem ser expostos e valorizados pela comunidade.",
    media: {
      url: "https://images.unsplash.com/photo-1503602642458-232111445657?w=640&h=480&fit=crop",
      alt_text: "Pessoa trabalhando com artesanato manual",
      caption: null,
    },
    created_at: "2026-03-15T00:00:00+00:00",
  },
  {
    id: 9,
    slug: "leitura-guiada",
    likes: 14,
    title: "Leitura guiada",
    content: "A leitura guiada estimula a imaginação, amplia o vocabulário e desenvolve a capacidade de interpretação, promovendo momentos de reflexão e aprendizado coletivo.",
    media: {
      url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=640&h=480&fit=crop",
      alt_text: "Pessoa lendo um livro em ambiente tranquilo",
      caption: null,
    },
    created_at: "2026-03-10T00:00:00+00:00",
  },
];